name: helm-example
system: example
environment: dev
namespace: default
appVersion: latest

deployment:
  scheduling: false
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 1

envs:
  DEBUG: false
  PORT: 80
