apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name }} 
    environment: {{ .Values.environment }}
    appVersion: {{ .Values.appVersion }}
data:
  ENVIRONMENT: {{ required "Value 'environment' is required" .Values.environment | quote }}
{{- if $.Values.deployment.scheduling }}
  SCHEDULING_ENABLED :  "true"
{{- else }}
  SCHEDULING_ENABLED :  "false"
{{- end }}
{{- range $key, $value := .Values.envs  }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
