apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.name }}
    environment: {{ .Values.environment }}
    appVersion: {{ .Values.appVersion }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
